AlignHash:
  EnforcedHashRocketStyle: table

AllCops:
  Excludes:
    - db/schema.rb
  RunRailsCops: true

AssignmentInCondition:
  AllowSafeAssignment: true

ClassAndModuleChildren:
  Enabled: false

Documentation:
  Enabled: false

LineLength:
  Enabled: false

MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

MethodLength:
  Max: 15

PredicateName:
    NamePrefixBlacklist:
      - foo_

StringLiterals:
  Enabled: false

TrailingComma:
  EnforcedStyleForMultiline: comma
