AlignHash:
  EnforcedHashRocketStyle: table

AssignmentInCondition:
    AllowSafeAssignment: true

ClassAndModuleChildren:
  Enabled: false

Documentation:
  Enabled: false

LineLength:
  Enabled: false

MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

PredicateName:
    NamePrefixBlacklist:
      - foo_

StringLiterals:
  Enabled: false
